server {
    listen 80;

    # 1. 프론트엔드 정적 파일 서빙
    location / {
        root   /usr/share/nginx/html;
        index  index.html index.htm;
        try_files $uri $uri/ /index.html;
    }

    # 2. 백엔드 API 프록시 설정 (Reverse Proxy)
    location /api/ {
        # receipt-backend-svc는 쿠버네티스 서비스 이름입니다.
        proxy_pass http://receipt-backend-svc:80/; 
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}
