pipeline {
    agent {
        kubernetes {
            yaml """
apiVersion: v1
kind: Pod
spec:
  # DNS가 없는 내부망 환경을 위한 설정
  hostAliases:
  - ip: "192.168.1.13"  # 실제 Harbor 서버 IP로 반드시 수정하세요!
    hostnames:
    - "harbor.test.com"
  containers:
  - name: kaniko
    image: gcr.io/kaniko-project/executor:debug
    command: ["sleep"]
    args: ["99d"]
    volumeMounts:
      - name: kaniko-secret
        mountPath: /kaniko/.docker
  volumes:
    - name: kaniko-secret
      projected:
        sources:
          - secret:
              name: harbor-ingress-tls # 생성하신 docker-registry 타입의 Secret 이름
              items:
                - key: .dockerconfigjson
                  path: config.json
"""
        }
    }

    environment {
        // Harbor 정보 설정
        REGISTRY = "harbor.test.com"
        PROJECT  = "test-project"
        IMAGE    = "nginx-test"
    }

    stages {
        stage('Build and Push to Harbor') {
            steps {
                container('kaniko') {
                    // Jenkins Credentials에서 ID가 'harbor-creds'인 정보를 가져옴
                    withCredentials([usernamePassword(credentialsId: 'harbor-creds', usernameVariable: 'USER', passwordVariable: 'PASS')]) {
                        sh """
                        /kaniko/executor --context `pwd` \
                            --dockerfile `pwd`/dockerfile/Dockerfile \
                            --destination ${REGISTRY}/${PROJECT}/${IMAGE}:latest \
                            --insecure \
                            --skip-tls-verify
                        """
                    }
                }
            }
        steps {
        // 1. 배포용 레포지토리를 별도 폴더(deploy-repo)에 클론
        dir('deploy-repo') {
            git url: 'http://git.test.com/user/nginx-deploy.git',
                branch: 'main',
                credentialsId: 'git-creds'
            
            script {
                // 2. 클론된 폴더 안의 YAML 파일 수정
                // 변수 처리를 위해 큰따옴표(")를 사용하고 shell 변수와 구분하세요.
                sh """
                sed -i "s|${REGISTRY}/${PROJECT}/${IMAGE}:.*|${REGISTRY}/${PROJECT}/${IMAGE}:${env.BUILD_NUMBER}|g" yaml/deployment.yaml
                
                # 3. 변경 사항 확인 및 Push
                if [ -n "\$(git status --porcelain)" ]; then
                    git config user.email "jenkins@test.com"
                    git config user.name "jenkins"
                    git add .
                    git commit -m "image update: ${IMAGE}:${env.BUILD_NUMBER}"
                    git push origin main
                else
                    echo "No changes detected, skipping push."
                fi
                """
            }
        }
    }
            
 }
}
    
    post {
        success {
            echo "Successfully pushed ${IMAGE}:${env.BUILD_NUMBER} to Harbor!"
        }
        failure {
            echo "Build or Push failed. Please check the logs."
        }
    }
}
